name: pypi

# 任务触发
on:
  # 当 提交到当前仓库时立即运行
  push:
    tags:
      - 'v*'

jobs:
  # 自动打卡任务
  pypi:
    # 使用ubuntu作为运行的OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
           python-version: '3.8'
           architecture: "x64"
      
      - name: "Check Python Info"
        run: "which python && which pip"


      - name: "Setup Build"
        run: "pip install build"

      - name: "Build Package"
        run: "python -m build"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          draft: true
          token: ${{ secrets.REPO_RELEASE_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: ${{ vars.PYPI_API_URL }}
          packages_dir: dist/
